---
# tasks file for web_server
  - name: install httpd
    package:
            name: httpd
            state: present
  - package:
          name: php
          state: present

  - name: copy the web-pages
    copy:
            src: index.php
            dest: /var/www/html
  - name: start the services
    service:
            name: httpd
            state: restarted

